### ISSUE TITLE
Update distributions document and delete obsolete files

### ISSUE THREAD

**Issue by mohandev2** [open-hpi/openhpi#2731]
In the docs/openhpi.org, there are three files that have obsolete information. They are Status.md, openhpi_schedule.png and openhpi_schedule.svg. These could be removed. Also, Distributions.md has old information. This could be updated. RHEL7 has 3.7.0 now. Debian stable has 3.6.1 and testing has 3.8.0. Ubuntu also has 3.6.1

**Comment by HemanthBeecherla** [comment]
For Debian and Ubuntu we have provided the appropriate link to find out available latest openhpi package.
I think only change that goes to the table in Distibution.md is for RHEL7 row.
